# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\"5\n\x0bUnitRequest\x12\r\n\x05input\x18\x01 \x01(\x02\x12\x17\n\x08\x63\x61tegory\x18\x02 \x01(\x0e\x32\x05.Unit\",\n\x0cUnitResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02\x12\x0c\n\x04unit\x18\x02 \x01(\t*!\n\x04Unit\x12\x0e\n\nKILOMETERS\x10\x00\x12\t\n\x05MILES\x10\x01\x32?\n\x10\x43onverterService\x12+\n\x0c\x63onvertUnits\x12\x0c.UnitRequest\x1a\r.UnitResponseb\x06proto3')

_UNIT = DESCRIPTOR.enum_types_by_name['Unit']
Unit = enum_type_wrapper.EnumTypeWrapper(_UNIT)
KILOMETERS = 0
MILES = 1


_UNITREQUEST = DESCRIPTOR.message_types_by_name['UnitRequest']
_UNITRESPONSE = DESCRIPTOR.message_types_by_name['UnitResponse']
UnitRequest = _reflection.GeneratedProtocolMessageType('UnitRequest', (_message.Message,), {
  'DESCRIPTOR' : _UNITREQUEST,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:UnitRequest)
  })
_sym_db.RegisterMessage(UnitRequest)

UnitResponse = _reflection.GeneratedProtocolMessageType('UnitResponse', (_message.Message,), {
  'DESCRIPTOR' : _UNITRESPONSE,
  '__module__' : 'test_pb2'
  # @@protoc_insertion_point(class_scope:UnitResponse)
  })
_sym_db.RegisterMessage(UnitResponse)

_CONVERTERSERVICE = DESCRIPTOR.services_by_name['ConverterService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _UNIT._serialized_start=115
  _UNIT._serialized_end=148
  _UNITREQUEST._serialized_start=14
  _UNITREQUEST._serialized_end=67
  _UNITRESPONSE._serialized_start=69
  _UNITRESPONSE._serialized_end=113
  _CONVERTERSERVICE._serialized_start=150
  _CONVERTERSERVICE._serialized_end=213
# @@protoc_insertion_point(module_scope)
